# Generated by Django 3.0.2 on 2020-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Designates whether the user has a seller account or not.', verbose_name='Seller status'),
        ),
    ]
