# Generated by Django 3.0.2 on 2020-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200315_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(default=1, help_text='Designates the users Address line1.', max_length=100, verbose_name='User PINCODE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(default=1, help_text='Designates the users Address line 2.', max_length=100, verbose_name='User PINCODE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default=1, help_text='Designates the users PINCODE.', max_length=6, verbose_name='User PINCODE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', help_text='Designates the users Profile picture.', upload_to='profile_pics', verbose_name='User Profile Picture'),
        ),
    ]
