# Generated by Django 3.0.2 on 2020-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200315_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contactno',
            field=models.CharField(default=1234567890, max_length=10),
        ),
    ]
