# Generated by Django 3.0.7 on 2020-06-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contactno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
    ]
