# Generated by Django 3.0.7 on 2020-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200619_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
