# Generated by Django 3.0.7 on 2020-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_assignment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='selection_mode',
            field=models.IntegerField(choices=[(1, 'All Available'), (2, 'Least Busy'), (3, 'Random')], default=1),
            preserve_default=False,
        ),
    ]
