# Generated by Django 3.0.7 on 2020-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200619_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
