# Generated by Django 3.0.7 on 2020-06-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200619_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Issue'),
        ),
    ]
