# Generated by Django 3.0.7 on 2020-06-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200620_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
    ]
