# Generated by Django 3.0.7 on 2020-06-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_assignment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='completed',
        ),
    ]
